version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: use-http
    versions:
    - 1.0.16
    - 1.0.17
    - 1.0.18
    - 1.0.19
  - dependency-name: dotenv-webpack
    versions:
    - 6.0.0
    - 6.0.2
    - 6.0.4
    - 7.0.1
  - dependency-name: eslint-config-airbnb-typescript-prettier
    versions:
    - 4.1.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: final-form
    versions:
    - 4.20.1
- package-ecosystem: npm
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: fastify-swagger
    versions:
    - 4.0.0
    - 4.0.1
    - 4.1.0
    - 4.1.1
    - 4.2.0
    - 4.3.0
    - 4.3.1
    - 4.3.2
    - 4.3.3
    - 4.4.0
    - 4.4.1
    - 4.4.2
    - 4.5.0
    - 4.5.1
    - 4.6.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: fastify-cookie
    versions:
    - 5.1.0
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
