version: '3'
services:
  mongodb:
    container_name: krawumms-mongo
    image: mongo:4.0.11
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - .tmp/data/db:/data/db
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - "27017:27017"
