version: 1
update_configs:
  - package_manager: javascript
    directory: "/frontend"
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: "development"
  - package_manager: javascript
    directory: "/backend"
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: "development"